name: "Docker: springboot"
on:
  push:
    branches:
      - '*'

jobs:
  build_and_publish:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and push Docker image
      env:
        COMMIT_HASH: ${{ github.sha }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t ppt
          docker tag ppt 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2027-ecr:$rev
          docker tag ppt 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2027-ecr:latest
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2027-ecr:latest
